# Generated by Django 5.0.2 on 2024-02-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_userprofile_number_alter_userprofile_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='account',
            field=models.CharField(choices=[('Current Account', 'Current Account'), ('Savings', 'Savings'), ('Business Account', 'Business Account')], default=1995, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cheque_book',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='credit_card',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='debit_card',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
