# Generated by Django 5.0.2 on 2024-02-27 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_userprofile_account_userprofile_cheque_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dob',
            field=models.DateField(default=datetime.date(2024, 2, 27)),
        ),
    ]
