# Generated by Django 5.0.2 on 2024-02-28 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_alter_userprofile_cheque_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cheque_book',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='credit_card',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='debit_card',
            field=models.BooleanField(default=False),
        ),
    ]
